name: 'tfcloud-publish-provider-action'
description: 'Publish a Terraform provider to Terraform Cloud'
author: 'Roy Osaki'

# Define your inputs here.
inputs:
  version:
    description: 'version'
    required: true
  keyid:
    description: 'key id'
    required: true
  orgName:
    description: 'organization name'
    required: true
  providerName:
    description: 'provider name'
    required: true

# Define your outputs here.
outputs:
  version:
    description: version
  files:
    description: files
  pwd:
    description: pwd

runs:
  using: node20
  main: dist/index.js
